mybatis:
  mapper-locations:classpath: mapper/*.xml
  type-aliases-package: com.chrise.demo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.202:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.1.202
    port: 6379
    password: 123456
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-wait: 1ms
        max-idle: 10
        min-idle: 5
nacos:
  config:
    server-addr: 192.168.1.202:8848
  discovery:
    server-addr: 192.168.1.202:8848